name: JMeter

on:
  # Lancement du workflow à chaque push ou pull sur la branche main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Autorisation de lancer manuellement le workflow
  workflow_dispatch:

# Actions du workflow
jobs:
  # Image Jmeter Docker api
  buildImage:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Prepare 📦
        id: prep
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/medhead-api-jmeter
          VERSION=latest
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=image::${DOCKER_IMAGE}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Show Image Settings 📦
        run: echo "IMAGE=${{ steps.prep.outputs.image }} VERSION=${{ steps.prep.outputs.version }} TAGS=${{ steps.prep.outputs.tags }}"

      - name: Set up Docker Buildx 📦
        uses: docker/setup-buildx-action@v1  
        
      #  Connexion Docker
      - name: Connexion Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Création image Docker
      - name: Docker Build only - retain local Image 📦
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          push: false
          tags: |
            ${{ steps.prep.outputs.tags }}
            ${{ steps.prep.outputs.image }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}


      # Tag image Docker
      - name: Tag Docker image
        run: docker tag medhead-api-jmeter:latest ${{ secrets.DOCKER_USERNAME }}/medhead-api-jmeter:latest

      # Envoi image à Docker Hub
      - name: Push to Docker repo (on Push only) ☁️
        if: ${{ github.event_name == 'push' }}
        run: docker image push --all-tags ${{ steps.prep.outputs.image }}
        
