name: JMeter

on:
  # Lancement du workflow à chaque push ou pull sur la branche main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Autorisation de lancer manuellement le workflow
  workflow_dispatch:

# Actions du workflow
jobs:
  # Image Jmeter Docker api
  buildImage:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Création image Docker
      - name: Build Docker image
        run: docker build --no-cache -t medhead-api-jmeter:latest -f Dockerfile .

      # Tag image Docker
      - name: Tag Docker image
        run: docker tag medhead-api-jmeter:latest ${{ secrets.DOCKER_USERNAME }}/medhead-api-jmeter:latest

      # Envoi image à Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/medhead-api:latest

      # Envoi image à Docker Hub
      - name: Run Docker image to Docker Hub
        run: docker run -it medhead-api-jmeter:latest
        
