name: JMeter

on:
  # Lancement du workflow à chaque push ou pull sur la branche main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Autorisation de lancer manuellement le workflow
  workflow_dispatch:

# Actions du workflow
jobs:
  # Image Jmeter Docker api
  buildImage:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Prepare 📦
        id: prep
        run: |
          DOCKER_IMAGE=justb4/jmeter
          VERSION="5.5"
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=image::${DOCKER_IMAGE}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Show Image Settings 📦
        run: echo "IMAGE=${{ steps.prep.outputs.image }} VERSION=${{ steps.prep.outputs.version }} TAGS=${{ steps.prep.outputs.tags }}"

      - name: Set up Docker Buildx 📦
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub 📦
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build only - retain local Image 📦
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          push: false
          tags: |
            ${{ steps.prep.outputs.tags }}
            ${{ steps.prep.outputs.image }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}

#      - name: TODO Tests with Docker Image ⚙️
#        run: docker run  --entrypoint "/run-tests.sh" ${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.version }}

      - name: Push to Docker repo (on Push only) ☁️
        if: ${{ github.event_name == 'push' }}
        run: docker image push --all-tags ${{ steps.prep.outputs.image }}
        
